/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.liquorsapp.views;

import javax.swing.*;
import com.liquorsapp.model.AdminModel;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ayushnabpoudel
 */




public class Liquorsapp extends javax.swing.JFrame {
    private List<AdminModel> drinkList = new LinkedList<>();
    private java.awt.CardLayout cardLayout;

    /**
     * Creates new form Liquorsapp
     */
    public Liquorsapp() {
        initComponents();
        initializeData();
        initializeLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        lblTitleHomePage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlMainWelcomePage = new javax.swing.JPanel();
        lblWelcomePagePic = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBackToLogin = new javax.swing.JButton();
        btnEnterWelcomePage = new javax.swing.JButton();
        pnlUserPage = new javax.swing.JPanel();
        pnlTitleUserPage = new javax.swing.JPanel();
        lblTitleUserPage = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlUserPageMain = new javax.swing.JPanel();
        btnSortBy = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplayDrinks = new javax.swing.JTable();
        txtFldCustomerNameUserPage = new javax.swing.JTextField();
        txtFldDrinkIdUserPage = new javax.swing.JTextField();
        txtFldQuantityUserPage = new javax.swing.JTextField();
        txtFldDrinkNameUserPage = new javax.swing.JTextField();
        btnOrderUserPage = new javax.swing.JButton();
        pnlAdminPage = new javax.swing.JPanel();
        pnlTitleAdminPage = new javax.swing.JPanel();
        lblTitleAdminPage = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        pnlMain1AdminPage = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDisplayDrinksAdminPage = new javax.swing.JTable();
        txtFldCalorieAdminPage = new javax.swing.JTextField();
        txtFldFlavorAdminPage = new javax.swing.JTextField();
        txtFldPriceAdminPage = new javax.swing.JTextField();
        txtFldDrinkIDAdminPage = new javax.swing.JTextField();
        txtFldDrinkNameAdminPage = new javax.swing.JTextField();
        btnCreateAdminPage = new javax.swing.JButton();
        btnDeleteAdminPage = new javax.swing.JButton();
        btnUpdateAdminPage = new javax.swing.JButton();
        btnLogOutAdminPage = new javax.swing.JButton();
        pnlMain2AdminPage = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUserDrinksAdminPage = new javax.swing.JTable();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        pnlAdminPageMain = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        pnlLoginMain = new javax.swing.JPanel();
        txtFldUsername = new javax.swing.JTextField();
        txtFldPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnGoToAdmin = new javax.swing.JButton();
        lblLoginTitle = new javax.swing.JLabel();
        lblTitleLoginPage = new javax.swing.JLabel();
        lblLoginPic1 = new javax.swing.JLabel();
        lblLoginPic = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));

        pnlTitle.setBackground(new java.awt.Color(0, 0, 0));
        pnlTitle.setForeground(new java.awt.Color(255, 255, 255));

        lblTitleHomePage.setBackground(new java.awt.Color(255, 255, 255));
        lblTitleHomePage.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblTitleHomePage.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleHomePage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleHomePage.setText("PRIME PULSE");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("H         Y         D         R         A         T         I         O         N");

        pnlMainWelcomePage.setBackground(new java.awt.Color(0, 0, 0));

        lblWelcomePagePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/83e18da0a1c01092cfd0f2f27cd9e187.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Hoefler Text", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html><p>Welcome to Prime Pulse!</p>\n<p>  </p>\n<p>Your ultimate solution for exploring and managing energy drinks with ease.\nDiscover flavors, check availability, and energize your day with Prime Pulse!\nEffortlessly manage inventory, track sales, and optimize stock for maximum efficiency.</p>\n<p>Let’s get started and redefine how energy drinks are managed and experienced!</p>\n<p>Thank you for keeping the energy flowing!</p>\n<p> </p>\n<p>Click the button below to get started and energize your journey!</p>\n</html>");

        btnBackToLogin.setFont(new java.awt.Font("Hoefler Text", 1, 24)); // NOI18N
        btnBackToLogin.setText("Back to Login");
        btnBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToLoginActionPerformed(evt);
            }
        });

        btnEnterWelcomePage.setFont(new java.awt.Font("Hoefler Text", 1, 24)); // NOI18N
        btnEnterWelcomePage.setText("ENTER");
        btnEnterWelcomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterWelcomePageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainWelcomePageLayout = new javax.swing.GroupLayout(pnlMainWelcomePage);
        pnlMainWelcomePage.setLayout(pnlMainWelcomePageLayout);
        pnlMainWelcomePageLayout.setHorizontalGroup(
            pnlMainWelcomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainWelcomePageLayout.createSequentialGroup()
                .addGroup(pnlMainWelcomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMainWelcomePageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(pnlMainWelcomePageLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnEnterWelcomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBackToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)))
                .addComponent(lblWelcomePagePic, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlMainWelcomePageLayout.setVerticalGroup(
            pnlMainWelcomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainWelcomePageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainWelcomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainWelcomePageLayout.createSequentialGroup()
                        .addComponent(lblWelcomePagePic, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlMainWelcomePageLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlMainWelcomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBackToLogin)
                            .addComponent(btnEnterWelcomePage))
                        .addGap(60, 60, 60))))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainWelcomePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMainWelcomePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlUserPage.setBackground(new java.awt.Color(116, 142, 99));

        pnlTitleUserPage.setBackground(new java.awt.Color(153, 176, 128));
        pnlTitleUserPage.setForeground(new java.awt.Color(255, 255, 255));

        lblTitleUserPage.setBackground(new java.awt.Color(255, 255, 255));
        lblTitleUserPage.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblTitleUserPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleUserPage.setText("PRIME PULSE");

        javax.swing.GroupLayout pnlTitleUserPageLayout = new javax.swing.GroupLayout(pnlTitleUserPage);
        pnlTitleUserPage.setLayout(pnlTitleUserPageLayout);
        pnlTitleUserPageLayout.setHorizontalGroup(
            pnlTitleUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitleUserPage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTitleUserPageLayout.setVerticalGroup(
            pnlTitleUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleUserPageLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitleUserPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        jTabbedPane1.setBackground(new java.awt.Color(31, 69, 41));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        pnlUserPageMain.setBackground(new java.awt.Color(31, 69, 41));

        btnSortBy.setBackground(new java.awt.Color(116, 142, 99));
        btnSortBy.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSortBy.setForeground(new java.awt.Color(255, 255, 255));
        btnSortBy.setText("SortBy");

        btnLogout.setBackground(new java.awt.Color(116, 142, 99));
        btnLogout.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        tblDisplayDrinks.setBackground(new java.awt.Color(178, 201, 173));
        tblDisplayDrinks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Flavor", "Stock"
            }
        ));
        jScrollPane1.setViewportView(tblDisplayDrinks);

        txtFldCustomerNameUserPage.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer Name"));
        txtFldCustomerNameUserPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldCustomerNameUserPageActionPerformed(evt);
            }
        });

        txtFldDrinkIdUserPage.setBorder(javax.swing.BorderFactory.createTitledBorder("Drink ID"));

        txtFldQuantityUserPage.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantity"));

        txtFldDrinkNameUserPage.setBorder(javax.swing.BorderFactory.createTitledBorder("Drink Name"));

        btnOrderUserPage.setBackground(new java.awt.Color(116, 142, 99));
        btnOrderUserPage.setText("ORDER");
        btnOrderUserPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderUserPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUserPageMainLayout = new javax.swing.GroupLayout(pnlUserPageMain);
        pnlUserPageMain.setLayout(pnlUserPageMainLayout);
        pnlUserPageMainLayout.setHorizontalGroup(
            pnlUserPageMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserPageMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserPageMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserPageMainLayout.createSequentialGroup()
                        .addGroup(pnlUserPageMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserPageMainLayout.createSequentialGroup()
                                .addComponent(btnSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(pnlUserPageMainLayout.createSequentialGroup()
                        .addGroup(pnlUserPageMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFldDrinkIdUserPage, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(txtFldDrinkNameUserPage, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(txtFldCustomerNameUserPage, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(txtFldQuantityUserPage, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(pnlUserPageMainLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnOrderUserPage, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlUserPageMainLayout.setVerticalGroup(
            pnlUserPageMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserPageMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserPageMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSortBy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFldCustomerNameUserPage, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFldDrinkIdUserPage, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFldDrinkNameUserPage, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFldQuantityUserPage, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnOrderUserPage, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Main ", pnlUserPageMain);

        javax.swing.GroupLayout pnlUserPageLayout = new javax.swing.GroupLayout(pnlUserPage);
        pnlUserPage.setLayout(pnlUserPageLayout);
        pnlUserPageLayout.setHorizontalGroup(
            pnlUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTitleUserPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        pnlUserPageLayout.setVerticalGroup(
            pnlUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTitleUserPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pnlAdminPage.setBackground(new java.awt.Color(116, 142, 99));

        pnlTitleAdminPage.setBackground(new java.awt.Color(153, 176, 128));
        pnlTitleAdminPage.setForeground(new java.awt.Color(255, 255, 255));

        lblTitleAdminPage.setBackground(new java.awt.Color(255, 255, 255));
        lblTitleAdminPage.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblTitleAdminPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleAdminPage.setText("PRIME PULSE");

        javax.swing.GroupLayout pnlTitleAdminPageLayout = new javax.swing.GroupLayout(pnlTitleAdminPage);
        pnlTitleAdminPage.setLayout(pnlTitleAdminPageLayout);
        pnlTitleAdminPageLayout.setHorizontalGroup(
            pnlTitleAdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitleAdminPage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTitleAdminPageLayout.setVerticalGroup(
            pnlTitleAdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleAdminPageLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitleAdminPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        jTabbedPane2.setBackground(new java.awt.Color(31, 69, 41));
        jTabbedPane2.setForeground(new java.awt.Color(255, 255, 255));

        pnlMain1AdminPage.setBackground(new java.awt.Color(31, 69, 41));

        tblDisplayDrinksAdminPage.setBackground(new java.awt.Color(178, 201, 173));
        tblDisplayDrinksAdminPage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Flavor", "Calorie"
            }
        ));
        jScrollPane2.setViewportView(tblDisplayDrinksAdminPage);

        txtFldCalorieAdminPage.setBorder(javax.swing.BorderFactory.createTitledBorder("Calorie"));
        txtFldCalorieAdminPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldCalorieAdminPageActionPerformed(evt);
            }
        });

        txtFldFlavorAdminPage.setBorder(javax.swing.BorderFactory.createTitledBorder("Flavor"));

        txtFldPriceAdminPage.setBorder(javax.swing.BorderFactory.createTitledBorder("Price"));

        txtFldDrinkIDAdminPage.setBorder(javax.swing.BorderFactory.createTitledBorder("Drink ID"));

        txtFldDrinkNameAdminPage.setBorder(javax.swing.BorderFactory.createTitledBorder("Drink Name"));

        btnCreateAdminPage.setBackground(new java.awt.Color(116, 142, 99));
        btnCreateAdminPage.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnCreateAdminPage.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateAdminPage.setText("CREATE");
        btnCreateAdminPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAdminPageActionPerformed(evt);
            }
        });

        btnDeleteAdminPage.setBackground(new java.awt.Color(116, 142, 99));
        btnDeleteAdminPage.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnDeleteAdminPage.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteAdminPage.setText("DELETE");
        btnDeleteAdminPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAdminPageActionPerformed(evt);
            }
        });

        btnUpdateAdminPage.setBackground(new java.awt.Color(116, 142, 99));
        btnUpdateAdminPage.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnUpdateAdminPage.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateAdminPage.setText("UPDATE");
        btnUpdateAdminPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAdminPageActionPerformed(evt);
            }
        });

        btnLogOutAdminPage.setBackground(new java.awt.Color(116, 142, 99));
        btnLogOutAdminPage.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnLogOutAdminPage.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOutAdminPage.setText("Log Out");
        btnLogOutAdminPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutAdminPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMain1AdminPageLayout = new javax.swing.GroupLayout(pnlMain1AdminPage);
        pnlMain1AdminPage.setLayout(pnlMain1AdminPageLayout);
        pnlMain1AdminPageLayout.setHorizontalGroup(
            pnlMain1AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMain1AdminPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMain1AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMain1AdminPageLayout.createSequentialGroup()
                        .addComponent(txtFldDrinkIDAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addGroup(pnlMain1AdminPageLayout.createSequentialGroup()
                        .addComponent(btnLogOutAdminPage)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMain1AdminPageLayout.createSequentialGroup()
                        .addGroup(pnlMain1AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlMain1AdminPageLayout.createSequentialGroup()
                                .addComponent(txtFldDrinkNameAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCreateAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMain1AdminPageLayout.createSequentialGroup()
                                .addComponent(txtFldCalorieAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlMain1AdminPageLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlMain1AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlMain1AdminPageLayout.createSequentialGroup()
                                        .addComponent(txtFldPriceAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(607, 607, 607)
                                        .addComponent(btnUpdateAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlMain1AdminPageLayout.createSequentialGroup()
                                        .addComponent(txtFldFlavorAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(607, 607, 607)
                                        .addComponent(btnDeleteAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(34, 34, 34))))
        );
        pnlMain1AdminPageLayout.setVerticalGroup(
            pnlMain1AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMain1AdminPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogOutAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFldDrinkIDAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlMain1AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFldDrinkNameAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlMain1AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFldPriceAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMain1AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMain1AdminPageLayout.createSequentialGroup()
                        .addComponent(txtFldFlavorAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFldCalorieAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDeleteAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Main", pnlMain1AdminPage);

        tblUserDrinksAdminPage.setBackground(new java.awt.Color(178, 201, 173));
        tblUserDrinksAdminPage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Drink ID", "Drink Name", "Quantity"
            }
        ));
        jScrollPane3.setViewportView(tblUserDrinksAdminPage);

        pnlAdminPageMain.setBackground(new java.awt.Color(31, 69, 41));

        javax.swing.GroupLayout pnlAdminPageMainLayout = new javax.swing.GroupLayout(pnlAdminPageMain);
        pnlAdminPageMain.setLayout(pnlAdminPageMainLayout);
        pnlAdminPageMainLayout.setHorizontalGroup(
            pnlAdminPageMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1037, Short.MAX_VALUE)
        );
        pnlAdminPageMainLayout.setVerticalGroup(
            pnlAdminPageMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("tab1", pnlAdminPageMain);

        javax.swing.GroupLayout pnlMain2AdminPageLayout = new javax.swing.GroupLayout(pnlMain2AdminPage);
        pnlMain2AdminPage.setLayout(pnlMain2AdminPageLayout);
        pnlMain2AdminPageLayout.setHorizontalGroup(
            pnlMain2AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMain2AdminPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlMain2AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMain2AdminPageLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane3)
                    .addContainerGap()))
        );
        pnlMain2AdminPageLayout.setVerticalGroup(
            pnlMain2AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMain2AdminPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(458, Short.MAX_VALUE))
            .addGroup(pnlMain2AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMain2AdminPageLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane3)
                    .addContainerGap()))
        );

        jTabbedPane2.addTab("Orders", pnlMain2AdminPage);

        javax.swing.GroupLayout pnlAdminPageLayout = new javax.swing.GroupLayout(pnlAdminPage);
        pnlAdminPage.setLayout(pnlAdminPageLayout);
        pnlAdminPageLayout.setHorizontalGroup(
            pnlAdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTitleAdminPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2))
                .addContainerGap())
        );
        pnlAdminPageLayout.setVerticalGroup(
            pnlAdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTitleAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1066, 1168));
        setMinimumSize(new java.awt.Dimension(89, 603));
        setSize(new java.awt.Dimension(1066, 1323));

        pnlLogin.setBackground(new java.awt.Color(31, 69, 41));

        pnlLoginMain.setBackground(new java.awt.Color(0, 0, 0));

        txtFldUsername.setBorder(javax.swing.BorderFactory.createTitledBorder("Username"));
        txtFldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldUsernameActionPerformed(evt);
            }
        });

        txtFldPassword.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));
        txtFldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldPasswordActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnGoToAdmin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnGoToAdmin.setText("Admin?");
        btnGoToAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToAdminActionPerformed(evt);
            }
        });

        lblLoginTitle.setFont(new java.awt.Font("Lao MN", 1, 18)); // NOI18N
        lblLoginTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginTitle.setText("LOGIN");

        lblTitleLoginPage.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblTitleLoginPage.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleLoginPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleLoginPage.setText("PRIME PULSE");

        lblLoginPic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2024-12-14 at 7.23.00 PM.png"))); // NOI18N
        lblLoginPic1.setText("jLabel2");

        lblLoginPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2024-12-14 at 7.23.00 PM.png"))); // NOI18N
        lblLoginPic.setText("jLabel2");

        javax.swing.GroupLayout pnlLoginMainLayout = new javax.swing.GroupLayout(pnlLoginMain);
        pnlLoginMain.setLayout(pnlLoginMainLayout);
        pnlLoginMainLayout.setHorizontalGroup(
            pnlLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginPic1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlLoginMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginMainLayout.createSequentialGroup()
                                .addComponent(lblTitleLoginPage)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginMainLayout.createSequentialGroup()
                                .addGroup(pnlLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGoToAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)))
                .addComponent(lblLoginPic, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlLoginMainLayout.setVerticalGroup(
            pnlLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLoginMainLayout.createSequentialGroup()
                        .addComponent(lblTitleLoginPage, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnGoToAdmin)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblLoginPic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
                    .addComponent(lblLoginPic1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aec0b2e22e71a03449676cd9e4f76da8.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/9cf8d46fd678459f060efb5189d835e1.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2df2e9d48b0ea48c3e53674c144ff2db.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/a06d9c06d03d86710f015a627259a873.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLoginMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLoginMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);
        getContentPane().add(pnlLogin, "LoginScreen");
        getContentPane().add(pnlMain, "MainScreen");
        getContentPane().add(pnlUserPage, "UserScreen");
        getContentPane().add(pnlAdminPage, "AdminScreen");
        loadScreen("LoginScreen");
    }
    

    private void addDrinks(AdminModel user){
        drinkList.add(user);
        DefaultTableModel addrow1 = (DefaultTableModel) tblDisplayDrinks.getModel();
        DefaultTableModel addrow2 = (DefaultTableModel) tblDisplayDrinksAdminPage.getModel();
        addrow1.addRow(new Object[]{user.getDrinkID(), user.getDrinkName(), user.getPrice(), user.getFlavor(), user.getCalorie()});
        addrow2.addRow(new Object[]{user.getDrinkID(), user.getDrinkName(), user.getPrice(), user.getFlavor(), user.getCalorie()});    
    }
    
     private void initializeData() {
        drinkList = new LinkedList();
        
        addDrinks(new AdminModel(1, "Prime", 99 , "Blueberry", 20));
        addDrinks(new AdminModel(2, "Red Bull", 99 , "Strawberry", 20));
    }
    
        

       
    
    
    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }
    
    private void btnBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToLoginActionPerformed
        // TODO add your handling code here:
        loadScreen("LoginScreen");
    }//GEN-LAST:event_btnBackToLoginActionPerformed

    private void txtFldCalorieAdminPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldCalorieAdminPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldCalorieAdminPageActionPerformed

    private void btnEnterWelcomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterWelcomePageActionPerformed
        // TODO add your handling code here:
        loadScreen("UserScreen");
    }//GEN-LAST:event_btnEnterWelcomePageActionPerformed

    private void btnCreateAdminPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAdminPageActionPerformed
        // TODO add your handling code here:
        int drinkId=Integer.parseInt(txtFldDrinkIDAdminPage.getText());
        String drinkName= txtFldDrinkNameAdminPage.getText();
        int price=Integer.parseInt(txtFldPriceAdminPage.getText());
        String flavor= txtFldFlavorAdminPage.getText();
        int calorie=Integer.parseInt(txtFldCalorieAdminPage.getText());

        try{
            if (txtFldDrinkIDAdminPage.getText().isEmpty() || txtFldDrinkNameAdminPage.getText().isEmpty() || txtFldPriceAdminPage.getText().isEmpty() || 
                 txtFldPriceAdminPage.getText().isEmpty() || txtFldCalorieAdminPage.getText().isEmpty()) {
                 JOptionPane.showMessageDialog(pnlLogin, "Please fill out all the fields","Failed", JOptionPane.WARNING_MESSAGE);
                 }
            
            else{
                if(drinkId<0 || drinkId>100){
                    JOptionPane.showMessageDialog(pnlUserPage, "Item not added. Drink ID must be between 0 and 100","Failed", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                if(price<0){
                    JOptionPane.showMessageDialog(pnlUserPage, "Item not added. Price cannot be negative","Failed", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                if(calorie<0 || calorie>100){
                    JOptionPane.showMessageDialog(pnlUserPage, "Item not added. Calorie must be between 0 and 100","Failed", JOptionPane.WARNING_MESSAGE);
                    return;
                }    
                }
            
            
            }
        
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(pnlUserPage, "Item not added. Please input valid data", "Failed", JOptionPane.WARNING_MESSAGE);
        }

        AdminModel drink = new AdminModel( drinkId,  drinkName,  price,  flavor,  calorie);
        addDrinks(drink);
        txtFldDrinkIDAdminPage.setText("");
        txtFldDrinkNameAdminPage.setText("");
        txtFldPriceAdminPage.setText("");
        txtFldFlavorAdminPage.setText("");
        txtFldCalorieAdminPage.setText("");

            
            

        
    }//GEN-LAST:event_btnCreateAdminPageActionPerformed

    private void btnLogOutAdminPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutAdminPageActionPerformed
        // TODO add your handling code here:
        loadScreen("LoginScreen");
    }//GEN-LAST:event_btnLogOutAdminPageActionPerformed

    private void btnGoToAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToAdminActionPerformed
        // TODO add your handling code here:
        loadScreen("AdminScreen");
    }//GEN-LAST:event_btnGoToAdminActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username= txtFldUsername.getText();
        String password= txtFldPassword.getText();

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(pnlLogin, "Please fill out all the fields","Failed", JOptionPane.WARNING_MESSAGE);
        }
        else{

            loadScreen("MainScreen");
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtFldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldPasswordActionPerformed

    private void txtFldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldUsernameActionPerformed
    
    private void btnOrderUserPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderUserPageActionPerformed
        // TODO add your handling code here:
        int id=Integer.parseInt(txtFldDrinkIdUserPage.getText());
        int quantity=Integer.parseInt(txtFldQuantityUserPage.getText());
        String cname= txtFldCustomerNameUserPage.getText();
        String dname= txtFldDrinkNameUserPage.getText();
        
        try{
            if (txtFldCustomerNameUserPage.getText().isEmpty() || txtFldDrinkIdUserPage.getText().isEmpty() || txtFldDrinkNameUserPage.getText().isEmpty() || 
                 txtFldQuantityUserPage.getText().isEmpty()) {
            JOptionPane.showMessageDialog(pnlLogin, "Please fill out all the fields","Failed", JOptionPane.WARNING_MESSAGE);
            }
            else{
                if(id<0 || id>100){
                    JOptionPane.showMessageDialog(pnlUserPage, "Order not placed. Drink ID must be between 0 and 100","Failed", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                if(quantity<0 || quantity>100){
                    JOptionPane.showMessageDialog(pnlUserPage, "Order not placed. Quantity must be between 0 and 100","Failed", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            DefaultTableModel fororder = (DefaultTableModel) tblUserDrinksAdminPage.getModel();
            fororder.addRow(new Object[]{cname, id, dname, quantity});

       
            txtFldDrinkIdUserPage.setText("");
            txtFldQuantityUserPage.setText("");
            txtFldCustomerNameUserPage.setText("");
            txtFldDrinkNameUserPage.setText(""); 
            JOptionPane.showMessageDialog(pnlUserPage, "Order successfully placed.", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }
        catch(NumberFormatException lecturererror){
                    JOptionPane.showMessageDialog(pnlUserPage, "Order not placed. Please input valid data", "Failed", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnOrderUserPageActionPerformed

    private void txtFldCustomerNameUserPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldCustomerNameUserPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldCustomerNameUserPageActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        txtFldUsername.setText("");
        txtFldPassword.setText("");
        loadScreen("LoginScreen");
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void deleteSelectedRow() {
    int selectedRow = tblDisplayDrinksAdminPage.getSelectedRow();
    if (selectedRow != -1) { 
        DefaultTableModel deleterow1 = (DefaultTableModel) tblDisplayDrinksAdminPage.getModel();
        DefaultTableModel deleterow2 = (DefaultTableModel) tblDisplayDrinks.getModel();
        deleterow1.removeRow(selectedRow); 
        deleterow2.removeRow(selectedRow);
    } else {
        JOptionPane.showMessageDialog(pnlAdminPage, "Please select a row to delete.","Failed", JOptionPane.INFORMATION_MESSAGE); 
    }
}
    
    private void btnDeleteAdminPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAdminPageActionPerformed
        // TODO add your handling code here:
        deleteSelectedRow();
    }//GEN-LAST:event_btnDeleteAdminPageActionPerformed

    
    
    
    private void btnUpdateAdminPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAdminPageActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnUpdateAdminPageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Liquorsapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Liquorsapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Liquorsapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Liquorsapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Liquorsapp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToLogin;
    private javax.swing.JButton btnCreateAdminPage;
    private javax.swing.JButton btnDeleteAdminPage;
    private javax.swing.JButton btnEnterWelcomePage;
    private javax.swing.JButton btnGoToAdmin;
    private javax.swing.JButton btnLogOutAdminPage;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOrderUserPage;
    private javax.swing.JButton btnSortBy;
    private javax.swing.JButton btnUpdateAdminPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lblLoginPic;
    private javax.swing.JLabel lblLoginPic1;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblTitleAdminPage;
    private javax.swing.JLabel lblTitleHomePage;
    private javax.swing.JLabel lblTitleLoginPage;
    private javax.swing.JLabel lblTitleUserPage;
    private javax.swing.JLabel lblWelcomePagePic;
    private javax.swing.JPanel pnlAdminPage;
    private javax.swing.JPanel pnlAdminPageMain;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlLoginMain;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMain1AdminPage;
    private javax.swing.JPanel pnlMain2AdminPage;
    private javax.swing.JPanel pnlMainWelcomePage;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JPanel pnlTitleAdminPage;
    private javax.swing.JPanel pnlTitleUserPage;
    private javax.swing.JPanel pnlUserPage;
    private javax.swing.JPanel pnlUserPageMain;
    private javax.swing.JTable tblDisplayDrinks;
    private javax.swing.JTable tblDisplayDrinksAdminPage;
    private javax.swing.JTable tblUserDrinksAdminPage;
    private javax.swing.JTextField txtFldCalorieAdminPage;
    private javax.swing.JTextField txtFldCustomerNameUserPage;
    private javax.swing.JTextField txtFldDrinkIDAdminPage;
    private javax.swing.JTextField txtFldDrinkIdUserPage;
    private javax.swing.JTextField txtFldDrinkNameAdminPage;
    private javax.swing.JTextField txtFldDrinkNameUserPage;
    private javax.swing.JTextField txtFldFlavorAdminPage;
    private javax.swing.JTextField txtFldPassword;
    private javax.swing.JTextField txtFldPriceAdminPage;
    private javax.swing.JTextField txtFldQuantityUserPage;
    private javax.swing.JTextField txtFldUsername;
    // End of variables declaration//GEN-END:variables
}
